apps/cart/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url
from cart.views import CartAddview, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    url(r'^add&', CartAddview.as_view(), name='add'),  # 购物车页面
    url(r'^$', CartInfoView.as_view(), name='cart'),  # 显示购物车页
    url(r'^update$', CartUpdateView.as_view(), name='update'),  # 购物车数据更新
    url(r'^delete$', CartDeleteView.as_view(), name='delete'),  # 删除购物车中的商品记录
]

apps/goods/urls.py
from goods.views import IndexView,DetailView,ListView
from django.conf.urls import url

urlpatterns = [
    # 商品界面  直接显示  所以匹配全部
    # url(r'^$',views.index,name='index') #首页
    url(r'^index/$', IndexView.as_view(),name='index'),  # 商品页作为首页
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页
]

apps/order/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from order.views import OrderPlaceView, OrderCommitView, OrderPayView, CheckPayView, OrderCommentView

urlpatterns = [
    url(r'^place$', OrderPlaceView.as_view(), name='place'),  # 提交订单显示
    url(r'^commit$', OrderCommitView.as_view(), name='commit'),  # 订单创建
    url(r'^pay$', OrderPayView.as_view(), name='pay'),  # 订单支付
    url(r'^check$', CheckPayView.as_view(), name='ckeck'),  # 查询支付交易结果
    url(r'^comment/(?P<order_id>.+)$', OrderCommentView.as_view(), name='comment'),  # 订单评论
]

apps/user/urls.py
from django.contrib.auth.decorators import login_required
from user.views import ActiveView ,LoginView, RegisterView, AddressView,UserInfoView,UserOrderView
from django.conf.urls import url


urlpatterns = [
    # url(r'^register$',views.register,name='register'),
    # url(r'^register_handle$',views.register_handle,name='register_handle'),
    url(r'^register$',RegisterView.as_view(),name='register'),#注册 功能
    url(r'^active/(?P<token>.*)$',ActiveView.as_view(),name='active'), #用户激活
    url(r'^login$',LoginView.as_view(),name='login'), #登录
    url(r'^logout$',LoginView.as_view(),name='logout'), #注销登录
    url(r'^$', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
    url(r'^order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    url(r'^address/$', AddressView.as_view(), name='address'),  # 用户中心-地址页


]

dailyfresh/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^search',include('haystack.urls')),
    url(r'^user/',include(('user.urls','user'),namespace='user')),#用户
    url(r'^cart/',include(('cart.urls','cart'),namespace='cart')),#购物车
    url(r'^order/',include(('order.urls','order'),namespace='order')),#订单
    url(r'^',include(('goods.urls','goods'),namespace='goods')),#商品  放最后    匹配时是由上到下
]

apps/cart/models.py
from django.db import models

# Create your models here.
# cart 使用redis存储

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse

from goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin

# Create your views here.
# 添加商品到购物车
# 1) 请求方式，采用ajax post
#    如果涉及到数据的修改(新增，更新，删除),采用post
#    如果涉及到数据的获取, 采用get
# 2) 传递参数：商品id 商品数量


# ajax发起的请求都在后台, 在浏览器中看不到效果
# /cart/add
class CartAddview(View):
    """购物车记录添加"""
    def post(self, request):
        user = request.user
        #判断登录
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        # 接收数据 商品id  数量
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')
        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 校验添加的商品数量
        # noinspection PyBroadException
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})
        # 业务处理：添加购物车记录
        #redis 存贮 购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id的值 -> hget cart_key 属性: cart_key[sku_id]
        # 如果sku_id在hash中不存在，hget返回None
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # redis中存在该商品，进行数量累加
            count += int(cart_count)
        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        # 设置hash中sku_id对应的值
        # hset ->如sku_id存在,更新数据,如sku_id不存在，追加数据
        conn.hset(cart_key, sku_id, count)

        # 获取用户购物车中的条目数
        cart_count = conn.hlen(cart_key)
        # 返回应答
        return JsonResponse({'res': 5, 'cart_count': cart_count, 'message': '添加成功'})

# /cart/
class CartInfoView(LoginRequiredMixin, View):
    """购物车显示"""
    def get(self, request):
        user = request.user
        # 获取用户购物车的商品信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # {'商品id': 商品数量}
        cart_dict = conn.hgetall(cart_key)
        print(cart_dict)

        skus = []
        # 保存用户购物车中商品总数目和总价格
        total_count = 0
        total_price = 0
        # 遍历获取商品信息
        for sku_id, count in cart_dict.items():
            # 根据商品id获取商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price * int(count)
            # 动态给sku对象添加一个属性amount,保存商品小计
            sku.amount = amount
            # 动态给sku对象添加一个属性,保存购物车中对应商品的数量
            sku.count = int(count)

            # 添加
            skus.append(sku)

            # 累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        # 组织上下文
        context = {'total_count': total_count,
                   'total_price': total_price,
                   'skus': skus}

        return render(request, 'cart.html', context)


# 更新购物车记录
# 采用ajax post请求
# 前端需要传递的参数: 商品id(sku_id) 更新商品数量(count)
# /cart/update
class CartUpdateView(View):
    """购物车记录更新"""
    def post(self, request):



        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})


        # 接收数据
        # sku_id = request.POST.get('sku_id')
        # count = request.POST.get('count')
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        # noinspection PyBroadException
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理: 更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数{'1':5,'2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '更新成功'})


# 删除购物车记录
# 采用ajax post请求
# 前端需要传递的参数: 商品id(sku_id)
# /cart/delete
class CartDeleteView(View):
    """购物车记录删除"""
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收参数
        sku_id = request.POST.get('sku_id')

        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理: 删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数{'1':5,'2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res': 3, 'total_count': total_count, 'message': '删除成功'})

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>
        {% block title %}{% endblock title %}
    </title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{% block topfiles %} {% endblock topfiles %}
</head>
<body>
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{# 判断登录 #}
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em><a href="#">{{ user.username }}</a></em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}

{# 网页搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="/index" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			    <input type="submit" class="input_btn fr" name="" value="搜索">

            </form>
		</div>

    {% block cart_bar %}
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
            {% if cart_count %}
			    <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
            {% else %}
                <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
            {% endif %}
		</div>
    {% endblock cart_bar %}

	</div>
{% endblock search_bar %}


{# 网页主体内容块 #}
{% block body %}{% endblock body %}

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2019-2020 best All Rights Reserved</p>
    <p>电话：010-****888    京ICP备*******8号</p>
</div>

{# 网页底部html元素块 #}
{% block bottom %} {% endblock bottom %}

{# 网页底部引入文件块 #}
{% block bottomfiles %} {% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{# 网页主体内容块 #}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class = "{{ type.logo }}">{{ type.name}}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页 列表页 主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_user_center.html
{# 用户中心-3个页面 #}
{% extends 'base.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}

{# 网页搜索框块 #}
{% block cart_bar %}{% endblock cart_bar %}

{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心-右侧内容块 #}
		{% block right_content %}{% endblock right_content %}
	</div>
{% endblock body %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in index_banner %}
                    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banner %}
			<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {# 首页展示分类文字商品信息 #}
                {% for banner in type.title_banner %}
                    <a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banner %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {# {% for sku in skus_page.object_list %}  如下一样的#}
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
            {# 有上一页 #}
                {% if skus_page.has_previous %}
                    <a href="{% url 'goods:list' type.id skus_page.previous_page_number%}?sort={{ sort }}">上一页</a>
                {% endif %}

            {% for pageindex in skus_page.paginator.page_range %}
                {% if pageindex == skus_page.number %}
                    <a href="{% url 'goods:list' type.id pageindex %}?sort={{ sort }}" class="active">{{ pageindex }}</a>
                {% else %}
                    <a href="{% url 'goods:list' type.id pageindex %}?sort={{ sort }}">{{ pageindex }}</a>
                {% endif %}
            {% endfor %}

            {# 有下一页 #}
            {% if skus_page.has_next %}
                <a href="{% url 'goods:list' type.id skus_page.next_page_number  %}?sort={{ sort }}">下一页</a>
            {% endif %}
            
			</div>
		</div>
	</div>
{% endblock main_content %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天生鲜-注册{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="{% url 'user:register' %}">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册" name="">
                        </li>
                    </ul>
                    {{ errmsg }}
				</form>
			</div>
		</div>
	</div>
{% endblock body %}

templates/user_center_order.html
{% extends 'base_user_center.html' %}
{% load static %}
{% block right_content %}
    <div class="right_content clearfix">
        {% csrf_token %}
        <h3 class="common_title2">全部订单</h3>

        {% for order in order_page %}
        <ul class="order_list_th w978 clearfix">
            <li class="col01">{{ order.create_time }}</li>
            <li class="col02">订单号：{{ order.order_id }}</li>
            <li class="col02 stress">{{ order.status_name }}</li>
        </ul>

        <table class="order_list_table w980">
            <tbody>
                <tr>
                    <td width="55%">
                        {% for order_sku in order.order_skus %}
                        <ul class="order_goods_list clearfix">
                            <li class="col01"><img src="{{ order_sku.sku.image.url }}"></li>
                            <li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }}元/{{ order_sku.sku.unite }}</em></li>
                            <li class="col03">{{ order_sku.count }}</li>
                            <li class="col04">{{ order_sku.amount }}元</li>
                        </ul>
                        {% endfor %}
                    </td>
                    <td width="15%">{{ order.total_price |add:order.transit_price }}(含运费:{{ order.transit_price }})元</td>
                    <td width="15%">{{ order.status_name }}</td>
                    <td width="15%"><a href="javascript:;" order_id="{{ order.order_id }}" status="{{ order.order_status }}" class="oper_btn">去付款</a></td>
                </tr>
            </tbody>
        </table>
        {% endfor %}

        <div class="pagenation">
            {% if order_page.has_previous %}
                <a href="{% url 'user:order' order_page.previous_page_number %}"> < 上一页</a>
            {% endif %}
            {% for pindex in pages %}
                {% if pindex == order_page.number %}
                    <a href="{% url 'user:order' pindex %}" class="active">{{ pindex }}</a>
                {% else %}
                    <a href="{% url 'user:order' pindex %}">{{ pindex }}</a>
                {% endif %}
            {% endfor %}
            {% if order_page.has_next %}
                <a href="{% url 'user:order' order_page.next_page_number %}">下一页></a>
            {% endif %}
        </div>
    </div>
{% endblock right_content %}

{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $('.oper_btn').each(function () {
            // 获取status
            status = $(this).attr('status')
            if (status == 1){
                $(this).text('去支付')
            }
            else if (status == 4){
                $(this).text('去评价')
            }
            else if (status == 5){
                $(this).text('已完成')
            }
        })


        $('.oper_btn').click(function () {
            // 获取status
            status = $(this).attr('status')
            // 获取订单id
            order_id = $(this).attr('order_id')
            if (status == 1){
                // 进行支付
                csrf = $('input[name="csrfmiddlewaretoken"]').val()
                // 组织参数
                params = {'order_id': order_id, 'csrfmiddlewaretoken': csrf}
                // 发起ajax post请求, 访问/order/pay, 传递参数:order_id
                $.post('{% url 'order:pay' %}', params, function (data) {
                    if (data.res == 3){
                        // 引导用户到支付页面
                        window.open(data.pay_url)
                        // 浏览器访问order/check,获取支付交易结果
                        // ajax post  传递参数:order_id
                        $.post('/order/check', params, function () {
                            if (data.res == 3){
                                alert('支付成功')
                                //重新加载
                                location.reload()
                            }
                            else{
                                alert(data.errmsg)
                            }
                        })
                    }
                    else{
                        alert(data.errmsg)
                    }
                })
            }
            else if (status == 4){
                //其他情况
                // 跳转到评价页面
                location.href = "/order/comment/"+order_id
            }
        })
    </script>
{% endblock bottomfiles %}

templates/user_center_site.html
{% extends 'base_user_center.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if address %}
						    <dd>{{ address.addr }} （{{ address.receiver }} 收） {{ address.phone }}</dd>
					    {% else %}
                            <dd>无地址信息</dd>
                        {% endif %}
                    </dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="{% url 'user:address' %}">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receiver">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
{% endblock right_content %}